services:
  embed:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.embed.rule=Host(`embed.ctrlaltparth.tech`)"
      - "traefik.http.routers.embed.entrypoints=websecure"
      - "traefik.http.routers.embed.tls.certresolver=mytlschallenge"
      - "traefik.http.services.embed.loadbalancer.server.port=8000"

networks:
  n8n_default:
    external: true
